subplot(2,2,1)
x = [-5:5:5]
y = sin(x)
plot(x,y)
title('sin(x)')
xticks([-5,0,5])
subplot(2,2,2)
y = cos(x)
plot(x,y)
title('cos(x)')
xticks([-5,0,5])
subplot(2,2,3)
y = csc(x)
plot(x,y)
title('csc(x)')
xticks([-5,0,5])
subplot(2,2,4)
y = sec(x)
plot(x,y)
title('sec(x)')
xticks([-5,0,5])